name = "DryToolingGranular"
uuid = "c4cd2e39-2c11-49af-bb08-d9d53d680cb6"
authors = ["Walter Dal'Maz Silva <walter.dalmazsilva@gmail.com>"]
version = "0.1.0"

[deps]
DryToolingCore = "8d904351-f17f-419c-aa8d-05d4f5cffd52"
